### ISSUE TITLE
Version 6.5.2 is released but Helm chart is still on version 6.4.4

### ISSUE THREAD

**Issue by dorianhhuc** [RocketChat/helm-charts#120]
Hello,

Can you update the Helm chart version to match the latest Rocket.Chat release?
It is lagging behind.

Best regards.

**Comment by dorianhhuc** [comment]
Is this repository still being maintained?

**Comment by zidex** [comment]
6.4.8 already released

**Comment by dorianhhuc** [comment]
I ended up just cloning the repo and deploying the new version myself...
But this issue still stands, the version in the original chart is not the latest release.

**Comment by conclusionlogic** [comment]
There's probably no need to clone or update the Rocket.Chat chart unless you need to modify templates to add support for new features.
You can set the new Rocket.Chat image version via the chart's [`image.tag`](https://github.com/RocketChat/helm-charts/blob/master/rocketchat/templates/chat-deployment.yaml#L57) value.

**Comment by dorianhhuc** [comment]
That's obviously true, although it's not a fix for this issue, it's a workaround.

The version now offered in the chart is not the latest version, and I think it's fair and reasonable to expect that it should be the latest version.

> There's probably no need to clone or update the Rocket.Chat chart unless you need to modify templates to add support for new features. You can set the new Rocket.Chat image version via the chart's [`image.tag`](https://github.com/RocketChat/helm-charts/blob/master/rocketchat/templates/chat-deployment.yaml#L57) value.

**Comment by dorianhhuc** [comment]
This issue is solved, thank you.
