### ISSUE TITLE
[Feature] Make PodDisruptionBudget optional even if replicas > 1

### ISSUE THREAD

**Issue by ccremer** [RocketChat/helm-charts#36]
Currently a [PodDisruptionBudget always gets deployed](https://github.com/RocketChat/helm-charts/blob/700490928aa719d8844dec26133513c0f9de0381/rocketchat/templates/poddisruptionbudget.yaml) if `replicaCount` is greater than 1. However, there's no way to disable this.

While PodDisruptionBudgets certainly have their reasons for existence, in our field we rather made "mixed" experiences. PDBs sometimes interfere with regular scheduled cluster maintenances, where every node is being drained and rebooted. PDBs often block or delay such reboots, so for our use cases a replicaCount of 2 or more with AntiAffinity is sufficient.

I propose an additional parameter like `podDisruptionBudget.enabled`, which is by default `true`. However, the condition to deploy a PDB is logical AND with `replicaCount` being greater than 1 (since deploying PDB with just 1 replica is even more "harmful" for node drains). That way we avoid breaking changes while still being able to disable a PDB.

What do you think? If this is acceptable, would work on this on your own or would you be interested in a PR?

**Comment by ccremer** [comment]
Any comments here?

**Comment by prppedro** [comment]
@ccremer, I've just added that flag you suggested — `podDisruptionBudget.enabled` and a conditional clause on PDB's template. Let me know if it works for you.

**Comment by ccremer** [comment]
Hi @prppedro 
Much appreciated. We'll be awaiting a new release then.
