### ISSUE TITLE
Deprecated Ingress API

### ISSUE THREAD

**Issue by mseiwald** [RocketChat/helm-charts#37]
The hosted chart (version 4.3.1) still uses `apiVersion: extensions/v1beta1` which is no longer served as of K8s 1.22. The git repo actually has this fixed but it's not in the released chart. I don't know where this discrepancy comes from.

Please fix this.

**Comment by snowball77** [comment]
IMHO the chart should be released again. It might make sense to make the chart (release) version independent of the actual application version as it is with other helm charts.

**Comment by snowball77** [comment]
I tested the new release 4.3.2 and this one works now. I assume with this we can close this issue?

**Comment by prppedro** [comment]
Yes, we've fixed that, a few releases back. I think we're good, for now. Closing the issue!
