### ISSUE TITLE
Allow for RocketChat Configuration On Helm Values

### ISSUE THREAD

**Issue by ChrisJBurns** [RocketChat/helm-charts#52]
Could we get added functionality to be able to configure RocketChat from the Helm chart?

This saves the manual work of having to go in and click through the initial setup wizard. Would be much easier if this was all automated as part of the RocketChat installation. Many other apps allow this to be done via Helm.

**Comment by MatthiasHertel** [comment]
Hi @ChrisJBurns 

u can do this with the `extraEnv:` in the `values.yaml`,  here u can overwrite every setting.
praefix your ENV var name with: `OVERWRITE_SETTING_`

Loc:
https://github.com/RocketChat/helm-charts/blob/master/rocketchat/values.yaml#L27
docs:
https://docs.rocket.chat/guides/administration/misc.-admin-guides/settings-via-env-vars

hopes it helps u
Matthias

**Comment by belmeopmenieuwesim** [comment]
`extraEnv` seems bugged. You always get this error when setting it in `values.yaml`:

```
Error: UPGRADE FAILED: template: rocketchat/templates/chat-deployment.yaml:139:7: executing "rocketchat/templates/chat-deployment.yaml" at <.>: wrong type for value; expect
ed string; got []interface {}
```

**Comment by jsnouffer** [comment]
> `extraEnv` seems bugged. You always get this error when setting it in `values.yaml`:
> 
> ```
> Error: UPGRADE FAILED: template: rocketchat/templates/chat-deployment.yaml:139:7: executing "rocketchat/templates/chat-deployment.yaml" at <.>: wrong type for value; expect
> ed string; got []interface {}
> ```

I also encountered this problem. Since "tpl" is used to render this section, it has to be a string. This works:
```
  extraEnv: |
    - name: INITIAL_USER
      value: yes
```
