### ISSUE TITLE
Rocketchat Kubernetes Websockt request 400

### ISSUE THREAD

**Issue by alb-dev** [RocketChat/helm-charts#6]
Hello Everyone,

i build a kubernetes cluster in my homelab via kubespray. Everything is working fine. After that i deployed the offical nginx-ingress from kubernetes.io which is acting as my ingress controller. I continued deploying my rocketchat via the helm chart from the stable helm repo which is sadly drepicated since november. Nervertheless the deployment worked. I can reach my rocketchat without a problem via browser and desktop app.

The only problem is the websockt connection. It seems like that the standard ingress dosent redirect the websocket properly. If i curl the service ip from within the cluster the /websocket does work without a problem. External i get a 400

Also the created wss url seems wrong: wss://my.chat.com/sockjs/431/rv3txed/websocket/

Am i doing something worng? Has anyone have a working setup with ingress?

Thanks in advance!

**Comment by prppedro** [comment]
Is this problem still affection the new versions?

**Comment by alb-dev** [comment]
@prppedro Hey. The issue resultet from the old stable helm chart repo version. I will deploy a new cluster for our internal Rocketchat in the upcoming weeks. I will report of the problem still exists. Best regards

**Comment by alb-dev** [comment]
The Problem is fixed. Everything works as expected
